version: '3.9'

services:
  sanity:
    build:
      context: ./sanity-studio
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    volumes:
      - ./sanity-studio:/app
    environment:
      - SANITY_STUDIO_PROJECT_ID=${SANITY_STUDIO_PROJECT_ID}
      - SANITY_STUDIO_DATASET=${SANITY_STUDIO_DATASET}
      - SANITY_STUDIO_API_VERSION=${SANITY_STUDIO_API_VERSION}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4321:4321"
    volumes:
      - ./frontend:/app
    environment:
      - SANITY_STUDIO_PROJECT_ID=${SANITY_STUDIO_PROJECT_ID}
      - SANITY_STUDIO_DATASET=${SANITY_STUDIO_DATASET}
      - SANITY_STUDIO_API_VERSION=${SANITY_STUDIO_API_VERSION}

  form-handler:
    build:
      context: ./form-handler
      dockerfile: Dockerfile
    ports:
      - "8787:8787"
    volumes:
      - ./form-handler:/app
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
